### ISSUE TITLE
Compiled and failed at unluac.jar extracting

### ISSUE THREAD

**Issue by zard777** [atom0s/HpkArchiver#2]
1) I've compiled your source code [here](https://github.com/zard777/Hacking_game_bunker/tree/master/VictorVran) -- unzip the file, you can see the standalone executable. 

2) I used that .exe to extract VVran's Lua.hpk (it works perfectly) 
3) I got the latest ver. of  **```unluac```** on [SourceForge](https://sourceforge.net/projects/unluac)
4) When I'm using this command 
```$ java -jar unluac_2015_06_13.jar path\to\Lua\Lua\Outfit.lua > decom_Outfit.lua```

It turned out errors like this: 
```
Exception in thread "main" java.lang.IllegalStateException: The input chunk reports an unsupported instruction size: 8 bytes
        at unluac.parse.LHeaderType.parse_instruction_size(LHeaderType.java:109)
        at unluac.parse.LHeaderType53.parse_main(LHeaderType.java:254)
        at unluac.parse.LHeaderType.parse(LHeaderType.java:45)
        at unluac.parse.BHeader.<init>(BHeader.java:66)
        at unluac.Main.file_to_function(Main.java:71)
        at unluac.Main.main(Main.java:42)
```

Can you please point out where my mistakes? I'm really appreciated that if the step-by-step guide was included. 

> 👍 Cheers !

**Comment by atom0s** [comment]
This tool is simply to just unarchive the files. The issues you are having with the Lua decompiler are not associated with this project so there isn't much I can do there to help.

**Comment by zard777** [comment]
It's okay, thanks for quickly response  👍

**Comment by Waterman1997** [comment]
@zard777 
Have you solved this problem, I have also encountered

**Comment by Waterman1997** [comment]
> 1. I've compiled your source code [here](https://github.com/zard777/Hacking_game_bunker/tree/master/VictorVran) -- unzip the file, you can see the standalone executable.
> 2. I used that .exe to extract VVran's Lua.hpk (it works perfectly)
> 3. I got the latest ver. of  **`unluac`** on [SourceForge](https://sourceforge.net/projects/unluac)
> 4. When I'm using this command
>    `$ java -jar unluac_2015_06_13.jar path\to\Lua\Lua\Outfit.lua > decom_Outfit.lua`
> 
> It turned out errors like this:
> 
> ```
> Exception in thread "main" java.lang.IllegalStateException: The input chunk reports an unsupported instruction size: 8 bytes
>         at unluac.parse.LHeaderType.parse_instruction_size(LHeaderType.java:109)
>         at unluac.parse.LHeaderType53.parse_main(LHeaderType.java:254)
>         at unluac.parse.LHeaderType.parse(LHeaderType.java:45)
>         at unluac.parse.BHeader.<init>(BHeader.java:66)
>         at unluac.Main.file_to_function(Main.java:71)
>         at unluac.Main.main(Main.java:42)
> ```
> Can you please point out where my mistakes? I'm really appreciated that if the step-by-step guide was included.
> 
> > 👍 Cheers !
@zard777 
Have you solved this problem, I have also encountered
